### ISSUE TITLE
not working (conflict with clang-formatter in cpptool package)

### ISSUE THREAD

**Issue by pollow** [welkineins/vscode-astyle#3]
Hi,

 I have vscode cpptools installed, and seems it uses clang-format by default, and I have no idea how to resolve the conflict and get the astyle working.

Thank you.

**Comment by welkineins** [comment]
Hi pollow,

It seems that currently vscode has no configuration for choosing language code formatting provider, but I notice that the latest installed provider will be the default one. 

You can uninstall and install astyle again to fix the problem for now. At the mean time, I'll looking for other solutions, e.g. provide different context menu option or keymap to trigger astyle formatter.

Thank you.

**Comment by pollow** [comment]
Thanks for your reply and your great work! I'll try to work around to solve
this problem.

**Comment by BillDenton** [comment]
With the latest version of you can disable the CLangFormat using:
Added option to disable clang-format-based formatting provided by this extension via "C_Cpp.formatting" : "disabled"
I've not tried it.

**Comment by welkineins** [comment]
Thanks to @BillDenton to provide a good solution for this issue. :)

I studied the VS code API, it's not support dominating formatter for one language. If you have multiple formatter with same match score, the later loaded one would be used.

### Reference
- https://code.visualstudio.com/Docs/extensionAPI/vscode-api

**Comment by BillDenton** [comment]
I don't think the disable works in C++/C extension. I've reported an issue https://github.com/Microsoft/vscode-cpptools/issues/469. So far I haven't managed to get Astyle formatting even after disabling the whole of the C++/C extension.

**Comment by BillDenton** [comment]
I was using the wrong way of disabling CLangFormat. It should be:
"C_Cpp.formatting": "disabled",
Now just got to get some Astyle options that I'm happy with!
